### ISSUE TITLE
Strange problem with cached pages 

### ISSUE THREAD

**Issue by rmvenancio** [prerender/prerender_rails#32]
Every time I made a new deploy of my app (rails + angular) all my cached pages (all of them cached before the deploy - 11 days ago) gets damaged. 

All cached pages will have the following error: 
Error compiling CSS Asset 
Sprockets::FileNotFound: couldn't find file 'bootstrat-sass-official') 

![screen shot 2016-05-13 at 20 15 53](https://cloud.githubusercontent.com/assets/10864133/15262737/250fce4a-195c-11e6-8c40-64670ff09033.png)

I can understand this error if it happen when caching pages happened at same time of deploy. But not the case. The deploy was yesterday and all pages was cached 11-to-16 days ago. 

Did you already saw something like that ? I need to delete all cached pages after a deploy ?. 
Is not the first time this is happening.

**Comment by thoop** [comment]
Sorry for the delay! If you have a new version number on your css file, I could see that you would get a 404 but I don't know why it would cause this error unless your rails is trying to generate that css file on the fly. Are you able to cache old css files on a new deploy for a short period to see if that's the case?

**Comment by rmvenancio** [comment]
Hi @thoop, 
I precompile the assets locally and the rsync to web server. 
I'm using capistrano.

**Comment by thoop** [comment]
Talking to you over email about this. For anyone else finding this in the future it looks like sprockets is returning a 200 for that CSS file but it setting the content of the `body` to the error shown above so the HTML is actually correct. I'd suggest setting up sprockets to return an actual 404 instead of the weird 200 with css clobbering the content. Ideally you'd cache old css for a short period or decreasing your cache freshness if you need us to recache pages more often.
