### ISSUE TITLE
Heroku h27 errors galore

### ISSUE THREAD

**Issue by trivett** [prerender/prerender_rails#35]
I just tried the Prerender service, and was soon faced with almost constant H27 - Client Request Interrupted from Heroku. I removed the prerender_rails gem and they ceased almost immediately. 

Is this a known issue? Possibly related to the fact that I wasn't yet paying for Prerender.io or a fault in my use of it? 

As always, very sorry if this is a known issue, it was just unexpected for me. 

Update: I re-added prerender to my app and signed up for a paid plan. Still getting loads of h27s. Anyone have an idea as to why? 

Update 2: A console error when testing locally that comes about now is really puzzling. This also went away when I removed prerender. 

```
Error: [$compile:tpload] Failed to load template: /assets/user/confirmation.html (HTTP status: -1 )

http://errors.angularjs.org/1.5.7/$compile/tpload?p0=%2Fassets%2Flistings%2Fsaa_apartment_item.html&p1=-1&p2=
    at angular.self-09d2205….js?body=1:69
    at handleError (angular.self-09d2205….js?body=1:19196)
    at processQueue (angular.self-09d2205….js?body=1:16171)
    at angular.self-09d2205….js?body=1:16187
    at Scope.$eval (angular.self-09d2205….js?body=1:17445)
    at Scope.$digest (angular.self-09d2205….js?body=1:17258)
    at Scope.scopePrototype.$digest (hint.js:1364)
    at Scope.$apply (angular.self-09d2205….js?body=1:17553)
    at Scope.scopePrototype.$apply (hint.js:1427)
    at done (angular.self-09d2205….js?body=1:11698)
```

No idea what an HTTP status of -1 is, but i suspect its the return for an indexOf? Really puzzling, and not sure whether I should continue with this pre-render thing. 

I'm on Rails 4.2.1, Ruby 2.2.6, Angular 1.5.7, using the latest version of the gem. Followed instructions in documentation to a T, or so I believe.

Any help or documentation to clarify what I may have screwed up is appreciated.

**Comment by thoop** [comment]
That's not a known issue. Which Rails server are you using to serve your app? Could it be the blocking I/O is causing that? We suggest you use Unicorn or Puma with enough workers so that a request from Prerender wouldn't be sent to the same server that is blocked on the Prerender response (if we are rendering a page on the fly).

**Comment by trivett** [comment]
Using Puma currently. Puma configs, pretty much boilerplate: 

```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

**Comment by thoop** [comment]
Can you send us a publicly available URL of your website? That way we can test with a local Prerender and see if we see any issues. Other than that, I think maybe the blocking I/O with a small number of servers might be the issue here. Feel free to send that URL to support@prerender.io if you want it to stay private.

**Comment by trivett** [comment]
Will do! I'll close this issue for now in case it's just noise for everyone else.
