### ISSUE TITLE
Calling prerender from the controller

### ISSUE THREAD

**Issue by rgraff** [prerender/prerender_rails#41]
This gem is probably better called `prerender_rack` as it can be used with an Rack compatible framework, not just Rails.

I like to be able to return prerender responses from inside my Rails controllers. Some of our URLs are impossible to whitelist from the Rack level.  I'm thinking of forking this gem and opening up a Pull Request.  Any guidance or thoughts before I do that?

Also how does the hosted service treat requests for prerendered pages that return redirects and non-2xx status?

Thanks, Robert

**Comment by thoop** [comment]
Yeah you're probably right :)

Could you explain a little more why they are impossible to whitelist from the Rack level? Do you need to run some business logic first instead of just whitelisting based on a string/regex?

The Prerender server will return whatever status code is returned from your server (it won't follow redirects) so that the crawlers can see the status code and properly update their index.

**Comment by rporrasluc** [comment]
A way simpler solution would be to allow the middleware to receive a Proc to get the the whitelist options you are interested in based in the current database status.

**Comment by rgraff** [comment]
@rporrasluc except that with a proc I would duplicate the logic already in my controller and have extra DB hits.

**Comment by rporrasluc** [comment]
Of course @rgraff, it depends a lot in your logic. In my opinion, and in my application, I prefer not to have logic for something as specific as SEO in my controllers, so I am happy with the solution offered by prerender.

If I were you, I would use the same regex used for routing to that controller to whitelist the routes you need, but I do not know how your app works, just giving ideas.
