### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by himberjack** [prerender/prerender_rails#46]
Why do you define the user-agents as non downcase and then every request to downcase them?
Would be more efficient to define them as downcase in advance AND make them symbols and just the incoming UA make downcase + symbol

**Comment by thoop** [comment]
Great question! That is a little weird that we stopped caring about the case but the intent was to always down case just in case someone overrode the list of user agents with a new user agent that had an uppercase. We didn't want that to seem like it would work but skip over the user agent just due to case. See: https://github.com/prerender/prerender_rails/pull/44

**Comment by himberjack** [comment]
Yet again, why not fixing this? to improve perf?
